const GLOBAL_TYPES = {
    SIGN_IN : 'SIGN_IN',
    SIGN_UP : 'SIGN_UP',
    RAISE_ALERT: 'RAISE_ALERT',
    DELETE_ALERT: 'DELETE_ALERT', 
    AUTH: 'AUTH',
    FILMS: 'FILMS',
    SERIES: 'SERIES',
    USER_INFO: 'USER_INFO',
    CLEAR_USER_INFO: 'CLEAR_USER_INFO',
    SEARCH_MOVIES: 'SEARCH_MOVIES'
}

export default GLOBAL_TYPES;